name: Build Atmosphere-NX
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Initialize and update submodules

      # Install devkitPro and dependencies
      - name: Install devkitPro
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential wget python3 python3-pip liblz4-dev
          wget https://apt.devkitpro.org/install-devkitpro-pacman
          sudo dpkg -i install-devkitpro-pacman
          sudo dkp-pacman -Syu
          sudo dkp-pacman -S switch-dev devkitA64 --noconfirm
          pip3 install pyelftools

      # Set up devkitPro environment variables
      - name: Set up devkitPro environment
        run: |
          echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
          echo "DEVKITARM=/opt/devkitpro/devkitARM" >> $GITHUB_ENV
          echo "DEVKITPPC=/opt/devkitpro/devkitPPC" >> $GITHUB_ENV

      # Build Atmosphere
      - name: Build Atmosphere
        run: |
          make -j$(nproc)

      # Create artifact directories
      - name: Prepare artifacts
        run: |
          mkdir -p artifacts/bootloader/payloads
          cp fusee/bin/fusee.bin artifacts/bootloader/payloads/
          cp -r out/* artifacts/

      # Upload artifacts
      - name: Upload Atmosphere artifacts
        uses: actions/upload-artifact@v4
        with:
          name: atmosphere-artifacts
          path: artifacts/
          if-no-files-found: error
          retention-days: 5

      # Optional: Commit artifacts to repository
      - name: Commit artifacts to repository
        if: github.event_name == 'push'  # Only run on push, not PR
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add artifacts/
          git commit -m "Add compiled Atmosphere artifacts"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
